// <auto-generated />
namespace AutoMax.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class abc123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abc123));
        
        string IMigrationMetadata.Id
        {
            get { return "201701081452584_abc123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
